version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"

  postgres_db:
    image: postgis/postgis
    environment:
      POSTGRES_USER: jkaub
      POSTGRES_PASSWORD: jkaub
      POSTGRES_DB: stations
#    volumes:
#      - ./db:/var/lib/postgresql/data
